### ISSUE TITLE
sql database

### ISSUE THREAD

**Issue by ayflorent** [akbardev94/si-uks-v0.2#1]
Hi,
There is no database structure file ?
Thanks

**Comment by akbardev94** [comment]
Hello,
I will give you database structure files on condition give me stars on github ?
Thanks

**Comment by hendar10** [comment]
tolong mas databasenya hendar10susanto@gmail.com thks

**Comment by akbardev94** [comment]
Wait for it, 
I have sent it to the email

**Comment by ayflorent** [comment]
Without the database file, the project cannot be viewed. While your answer is a condition, a star to get the database file. I cannot give a star for what I cannot even visualize. Thank you

**Comment by akbardev94** [comment]
Give me star + follow and send you database from apps on google drive

Sent from Anas M.A

________________________________

**Comment by ayflorent** [comment]
ok DONE

**Comment by akbardev94** [comment]
Can send your email ?

**Comment by ayflorent** [comment]
Yes Please

**Comment by hafidaprizal** [comment]
minta database nya mas.
terimakasih sebelumnya.

**Comment by akbardev94** [comment]
Emailnya mas

Sent from Anas M.A

________________________________

**Comment by akbardev94** [comment]
Your email bro

Sent from Anas M.A

________________________________

**Comment by iqbal-53** [comment]
mas udah aku beri star + follow ya.
ini email saya : iqbal.ramadhani53@gmail.com
thank you a lot mas

**Comment by nurfauzannf** [comment]
Thanks Om, ini email saya
nurfauzan2106@gmail.com

**Comment by akbardev94** [comment]
sudah kukirim lewat email kak

**Comment by ghost** [comment]
done gan, ditunggu di email palapanagari@gmail.com yaa gan. Terima kasih banyak gann

**Comment by hafidaprizal** [comment]
maaf email nya ketinggalan 
hafidaprizal888@gmail.com
btw saya sudah follow & stars

**Comment by akbardev94** [comment]
sudah aku kirim kak thanks untuk star dan follownya

**Comment by iqbal-53** [comment]
user adminnya apa ya?

**Comment by rohman84** [comment]
Klo mau dapet source code sama databasenya gimana ya?

**Comment by rohman84** [comment]
durrahman99elbant@gmail.com

**Comment by akbardev94** [comment]
Tinggal download aja klo source codex kak tekan code

Sent from Anas M.A

________________________________

**Comment by akbardev94** [comment]
Klo database follow dlu sma star
________________________________

**Comment by akbardev94** [comment]
username : adminUKS@gmail.com
Password : 12345

**Comment by Yosepheryana24** [comment]
Haloo gan saya sudah follow dan sudah kasih bintang , ini email sy gan : felixadrian1995@gmail.com .

**Comment by Luthfi98** [comment]
Sudah saya follow dan kasih bintatang, ihdalhusnayainluthfi@gmail.com

**Comment by akbardev94** [comment]
sudah kak di cek di gdrivenya masing2

**Comment by rezawara** [comment]
minta database nya gan ke guerez4@gmail.com
udh ane follow sma kasih star
mkasih yo

**Comment by Vernandahd** [comment]
start done, follow done. 
vernandahd@gmail.com

**Comment by masfata** [comment]
done follow & star

mamastat@gmail.com

**Comment by oktapiancaw** [comment]
Halo, Follow & star udah bang.
oxtcode00@gmail.com

**Comment by bagus-utomo** [comment]
Sudah follow dan star bang.
Ini email saya : bagusutomo144@gmail.com
Thanks

**Comment by ayflorent** [comment]
Resolved

**Comment by akbardev94** [comment]
Sudah liat di gdrive masing2 kak

**Comment by hendar10** [comment]
Kenapa pas login masuk kesini y

403
Akses Terlarang

← Back to Dashboard

**Comment by akbardev94** [comment]
Cbak pakai ignocito chrome

Sent from Anas M.A

________________________________

**Comment by akbardev94** [comment]
Sudah saya share semua coba di cek di gdrive

**Comment by rohman84** [comment]
belum ada bang


Pada tanggal Jum, 7 Agu 2020 pukul 20.02 Anas Maulana Akbar <
notifications@github.com> menulis:

**Comment by akbardev94** [comment]
Emailnya apa kak mungkin klewat

Sent from Anas M.A

________________________________

**Comment by rohman84** [comment]
durrahman99elbant@gmail.com

Pada tanggal Sab, 8 Agu 2020 pukul 08.54 Anas Maulana Akbar <
notifications@github.com> menulis:

**Comment by gibran-sitorus** [comment]
BG file databasenya kirimkan ke sahatsitorus3@gmail.com

**Comment by sirepson** [comment]
Bang boleh minta databasenya? arepp.son@gmail.com
